name: Minishell Tester

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Minishell
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev build-essential

      - name: Build Minishell
        run: make

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: minishell-x86_64
          path: minishell
          retention-days: 1

  testing-basic-minishell:
    name: Test minishell Basic
    runs-on: ubuntu-22.04
    needs: make
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libreadline-dev valac valgrind
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name : Chmod minishell BIN
        run: |
          chmod u+x minishell
      - name: Git clone tester
        run: git clone https://gitlab.com/nda-cunh/minishell_tester.git
      - name: compile tester and run
        run: |
          cd minishell_tester/
          make
          ./tester -j 1
  testing-leak-minishell:
    name: Test minishell Leaks
    runs-on: ubuntu-22.04
    needs: make
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libreadline-dev valac valgrind
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name : Chmod minishell BIN
        run: |
          chmod u+x minishell
      - name: Git clone tester
        run: git clone https://gitlab.com/nda-cunh/minishell_tester.git
      - name: compile tester and run
        run: |
          cd minishell_tester/
          make
          ./tester -v -j 1
  testing-fd-minishell:
    name: Test minishell FD
    runs-on: ubuntu-22.04
    needs: make
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libreadline-dev valac valgrind
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name : Chmod minishell BIN
        run: |
          chmod u+x minishell
      - name: Git clone tester
        run: git clone https://gitlab.com/nda-cunh/minishell_tester.git
      - name: compile tester and run
        run: |
          cd minishell_tester/
          make
          ./tester -vf -j 1