name: Minishell Tester

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Minishell
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev build-essential

      # 1. COMPILATION
      - name: Build Minishell
        run: make

      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: minishell-x86_64
          path: minishell
          retention-days: 1

jobs:
  make-tester:
    runs-on: ubuntu-22.04
    setps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libreadline-dev valac valgrind
      - name: Setup Tester
        run: |
          git clone https://gitlab.com/nda-cunh/minishell_tester.git
          cd tester_repo && make
      - name: Create artifact
        uses: actions/upload-artifact@v6
        with:
          name: tester-x86_64
          path: minishell_tester/tester
          retention-days: 1
jobs:
  basic:
    needs: [make, make-tester] 
    runs-on: ubuntu-22.04
    setps:
      - name: Download minishell
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name: Download tester
        uses: actions/download-artifact@v4
        with:
          name: tester-x86_64
          path: .
        
      # 2. RUN TESTS
      - name: Run All Tests
        run: |
          echo "Running Standard Tests..."
          ./tester -j 1 ./minishell > ./test_output.txt 2>&1 || true

      - name: Print Raw Logs
        run: |
          echo -e "\n--- STANDARD TEST LOGS ---"
          cat test_output.txt
    
jobs:
  leak:
    needs: [make, make-tester] 
    runs-on: ubuntu-22.04
    setps:
      - name: Download minishell
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name: Download tester
        uses: actions/download-artifact@v4
        with:
          name: tester-x86_64
          path: .
      - name: test
        run: |
          echo "Running Leak Tests (Valgrind)..."
          ./tester -v ./minishell > ./test_output_leaks.txt 2>&1 || true
      - name: Print
        run: |
          echo -e "\n--- LEAK TEST LOGS ---"
          cat test_output_leaks.txt
jobs:
  fd:
    needs: [make, make-tester] 
    runs-on: ubuntu-22.04
    setps:
      - name: Download minishell
        uses: actions/download-artifact@v4
        with:
          name: minishell-x86_64
          path: .
      - name: Download tester
        uses: actions/download-artifact@v4
        with:
          name: tester-x86_64
          path: .
      - name: test FD
        run: |
          echo "Running Leak Tests (Valgrind track-fd)..."
          ./tester -vf ../minishell > ../test_output_leaks_fd.txt 2>&1 || true
      - name: Print Raw Logs
        run: |
          echo -e "\n--- LEAK FD TEST LOGS ---"
          cat test_output_leaks_fd.txt